core/accounts/urls.py
from django.urls import path
from .views import login_view, register_view, logout_view
app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('todo.urls')),
]

core/todo/urls.py
from django.urls import path
from . import views
app_name = 'todo'


urlpatterns = [
    path('', views.list_view, name='task-list'),
    path('update/<int:pk>/', views.update_task, name='update-task'),
    path('complete/<int:pk>/', views.complete_task, name='complete-task'),
    path('delete/<int:pk>/', views.delete_task, name='delete-task'),
]

core/accounts/models.py
from django.db import models

# Create your models here.

core/todo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.title
    
    class Meta:
        order_with_respect_to = "user"
        

core/todo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
                "placeholder": "enter the title",
            }
        ),
        label="",
    )
    class Meta:
        model = Task
        fields = ('title',)

core/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def login_view(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(
                    request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect("/")
            else:
                return render(request, 'accounts/login.html', {'form': form})

        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)

    else:
        return redirect('/')


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


def register_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid:
                form.save()
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password1')
                user = authenticate(
                    request, username=username, password=password)

                if user is not None:
                    login(request, user)
                return redirect("/")
            else:
                return render(
                    request, 'accounts/register.html', {'form':form}
                )
        
        form = UserCreationForm()
        context = {'form': form}
        return render(request, 'accounts/register.html', context)
    else:
        return redirect('/')

core/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Task
from .forms import TaskForm
# Create your views here.


@login_required
def list_view(request):
    tasks = Task.objects.filter(user=request.user)
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(pk=request.user.id)
            obj.save()
        return redirect("/")

    context = {'tasks': tasks, 'form': form}
    return render(request, 'todo/task_list.html', context)


@login_required
def update_task(request, pk):
    task = get_object_or_404(Task, id=pk, user=request.user)
    form = TaskForm(instance=task)
    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(pk=request.user.id)
            obj.save()
            return redirect('/')

    context = {'form': form}
    return render(request, 'todo/update_task.html', context)

@login_required
def complete_task(request, pk):
    item = get_object_or_404(Task, id=pk, user=request.user)
    item.complete = True
    item.save()
    return redirect('/')


@login_required
def delete_task(request, pk):
    item = get_object_or_404(Task, id=pk, user=request.user)
    item.delete()
    return redirect('/')

core/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock %}

{% block content %}
<body>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <h2 class="mb-4">Login</h2>
          <form method="POST" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputEmail">Username</label>
              <input type="username" name="username" class="form-control" id="inputEmail" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="inputPassword">Password</label>
              <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Log in</button>
          </form>
          {% if form.errors %}
            <div class="alert alert-error">
            <h6>Please fix the following errors</h6>
            <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
            </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
          <p class="mt-3 mb-2">Dont have an account then? <a href="{% url 'accounts:register' %}">create one</a></p>
        </div>
      </div>
    </div>
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8vc"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
  </body>
{% endblock %}

core/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register Page{% endblock %}

{% block content %}
<body>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <h2 class="mb-4">SignUp</h2>
          <form method="POST" action="{% url 'accounts:register' %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputEmail">Username</label>
              <input type="username" name="username" class="form-control" id="inputEmail" placeholder="Enter username">
            </div>
            <div class="form-group">
              <label for="inputPassword">Password</label>
              <input type="password" name="password1" class="form-control" id="inputPassword" placeholder="Password">
            </div>
            <div class="form-group">
                <label for="inputPassword">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="inputPassword" placeholder="Password">
              </div>
            <button type="submit" class="btn btn-primary">Signup</button>
          </form>
          {% if form.errors %}
            <div class="alert alert-error">
            <h6>Please fix the following errors</h6>
            <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
            </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
          <p class="mt-3 mb-2">Already have an account then <a href="{% url 'accounts:login' %}"> login</a></p>
        </div>
      </div>
    </div>
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8vc"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>
  </body>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

core/templates/todo/task_list.html
{% extends 'base.html' %}
{% block title %}Task List{% endblock %}

{% block content %}
<div class="container py-5">
  
    <div class="row">
      <div class="col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}"><button class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Logout</button></a>
        {% else %}
        <a href="{% url 'accounts:login' %}"><button class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Login</button></a>
        {% endif %}


        <h1 class="text-center mb-4">Todo List</h1>

        <form method="POST" action="/">
            {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" name="title" class="form-control" placeholder="Enter task..." required>
            <div class="input-group-append">
              <button class="btn btn-primary" type="submit">Add Task</button>
            </div>
          </div>
        </form>
        {% for task in tasks%}
        <ul class="list-group">
          <li class="list-group-item d-flex justify-content-between align-items-center">
            {% if task.complete == True %}
            <strike>{{ task }}</strike>
            {% else %}
            <span>{{ task }}</span>
            {% endif %}
            <div>
              <a href="{% url 'todo:delete-task' task.id %}"><button class="btn btn-sm btn-danger mr-2">Delete</button></a>
              <a href="{% url 'todo:update-task' task.id %}"><button class="btn btn-sm btn-secondary mr-2">Edit</button></a>
              <a href="{% url 'todo:complete-task' task.id %}"><button class="btn btn-sm btn-success">Complete</button></a>
            </div>
          </li>
        </ul>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

core/templates/todo/update_task.html
{% extends 'base.html' %}

{% block title %}Edit Task{% endblock %}
{% block content %}
<div class="container my-5">
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}"><button class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Logout</button></a>
        {% else %}
        <a href="{% url 'accounts:login' %}"><button class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Login</button></a>
        {% endif %}

    <h1 class="text-center mb-5">Edit Task</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="task-name">Task Title</label>
                {{ form }}
        </div>
        <button type="submit" class="btn btn-primary mr-3"><i class="fas fa-save mr-2"></i>Save</button>
        <a href="{% url 'todo:task-list' %}"><button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times mr-2"></i>Cancel</button></a>
    </form>
</div>

{% endblock %}